Рабочая тетрадь №2

1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.3.1 Задача:Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
matrix = ([0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0])
for row in matrix:
  print(row)


[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


1.3.2 Задача: Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [ ]:
import numpy as np
A = np.arange(25).reshape(5,5)
A[1],A[2],A[3],A[4] = A[0],A[0],A[0],A[0]
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задача: Создать массив 3x3x3 со случайными значениями.


In [ ]:
import numpy as np
A = np.array(np.random.random((3,3,3)))
print(A)

[[[0.35892339 0.64627834 0.37965499]
  [0.17273958 0.42575335 0.64029317]
  [0.35350752 0.08788058 0.94249131]]

 [[0.29856341 0.35493908 0.43645339]
  [0.30280335 0.44026475 0.96314086]
  [0.7927805  0.51112237 0.53322115]]

 [[0.56131161 0.81194384 0.03690549]
  [0.64407755 0.65526422 0.94233752]
  [0.13008986 0.71550811 0.66427764]]]


1.3.4 Задача: Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
import numpy as np
print("Введите размер матрицы m*n через пробел")
m,n = list(map(int,input().split()))
for i in range (m):
  if (i == 0 or i == m-1):
    print(np.ones(n,dtype = int))
  else:
    A = np.zeros(n,dtype = int)
    A[0] = 1
    A[n-1] = 1
    print(A)

Введите размер матрицы m*n через пробел
8 8
[1 1 1 1 1 1 1 1]
[1 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 1]
[1 1 1 1 1 1 1 1]


1.3.5 Задача: Создайте массив и отсортируйте его по убыванию

In [ ]:
import numpy as np
print("Введите размер массива")
n = int(input())
A = np.array(np.random.random(n))
A = np.sort(A)
A = A[::-1]
print(A)

Введите размер массива
23
[0.90154245 0.88064547 0.86795806 0.84597655 0.8234138  0.79226975
 0.77671782 0.74862669 0.7186094  0.52303845 0.50298645 0.48533587
 0.46549608 0.44347279 0.44162342 0.42767024 0.41950195 0.38041032
 0.34852578 0.33857771 0.3038026  0.30027595 0.23129512]


1.3.6 Задача: Создайте матрицу, выведите ее форму, размер и размерность

In [ ]:
import numpy as np
import random
A = np.random.randint(np.random.randint(1,99), size = (random.randint(1,7), random.randint(1,6)))
print(A.ndim) # размерность
print(A.shape) #форма
print(A.size) #размер
print(A)

2
(3, 3)
9
[[28 34 22]
 [18 10 42]
 [ 7 34 42]]


2.2.1 Пример
Задача:
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [5]:
import pandas as pd
lst = [1,2,3,4,5]
d = {'a':1,'b':2,'c':3}
ndarr = np.array([1,2,3,4,5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


2.3.1 Задача: Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [ ]:
import random
import math
import numpy as np
import pandas as pd
s = random.randint(1,23)
A = [0]*s
B = [0]*len(A)
sum = 0
for i in range (len(A)):
  A[i] = random.random()
  B[i] = random.random()
  sum += abs(A[i] - B[i])**2
#print(A)
#print(B)
a = pd.Series(A)
b = pd.Series(B)
print(math.sqrt(sum))
print(np.linalg.norm(a-b))

0.7926016521511368
0.7926016521511368


2.3.2 Задача: Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

2.3.3 Задача:
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
print(pd.DataFrame(dataframe.head(5)))
print()
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[2:7]
dataframe.head(10)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa



sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
5         0.305556        1.957669              1.7             0.4  setosa
6         0.083333        0.800654              1.4             0.3  setosa
7         0.194444        0.800654              1.5             0.2  setosa
8         0.027778       -0.356361              1.4             0.2  setosa
9         0.166667        0.106445              1.5             0.1  setosa

3.2.1. Пример
Задача:
Прошкалируйте числовой признак в диапазон между двумя значениями.


In [7]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.3.2 Задание Задача:
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)

min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

dataframe['sepal_length_cm'] = min_max_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe['sepal_width_cm'] = standard_scaler.fit_transform(dataframe[['sepal_width_cm']])

dataframe.head(20)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0          0.222222        1.032057              1.4             0.2  setosa
1          0.166667       -0.124958              1.4             0.2  setosa
2          0.111111        0.337848              1.3             0.2  setosa
3          0.083333        0.106445              1.5             0.2  setosa
4          0.194444        1.263460              1.4             0.2  setosa
5          0.305556        1.957669              1.7             0.4  setosa
6          0.083333        0.800654              1.4             0.3  setosa
7          0.194444        0.800654              1.5             0.2  setosa
8          0.027778       -0.356361              1.4             0.2  setosa
9          0.166667        0.106445              1.5             0.1  setosa
10         0.305556        1.494863              1.5             0.2  setosa
11         0.138889        0.800654              1.6             0.2  setosa
12         0.138889       -0.124958              1.4             0.1  setosa
13         0.000000       -0.124958              1.1             0.1  setosa
14         0.416667        2.189072              1.2             0.2  setosa
15         0.388889        3.114684              1.5             0.4  setosa
16         0.305556        1.957669              1.3             0.4  setosa
17         0.222222        1.032057              1.4             0.3  setosa
18         0.388889        1.726266              1.7             0.3  setosa
19         0.222222        1.726266              1.5             0.3  setosa